language: ruby
cache: bundler
cache: yarn
addons:
  chrome: stable
before_install:
  - gem install bundler:2.0.1
install:
  - bundle install --jobs=3 --retry=3
  - yarn install
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
after_success:
  - "openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa"
  - "bundle exec cap production deploy"
env:
  global:
    secure: kB9R1aKL4B6mwYW9A4WSF2YXdylhypqPC2CwSWrMvj8kT8b87KKMH7PXBDexvGdvi1EX+AeiWoI5v2BAb8D1kR8osOXtP7oqAAPX82Z1BAlh8CRJRkt+BDGv+/gi4e563EFmvZ0iStVK2asV8nmccO1lqlHi/l829JWwdDhnF3smdKDcDmJV8Hx6s6lPlQdE/DW0jyj3aQJ0GX47QqxNGO3hFXy2pH9HqqXNLztJJut6JVaEm/gUgI47y0yafBca8IfBOih2yzEZHzhWq4PpCAqkAbwmkiVMviut4BPaQ6sm9roXHZMSJnhozY2PQTu6yRzYNCT4Mcui/X8q7fgNqVfWBpAGSC/W8RoE64MeBFmbF7IQN0Lxg9GxV1FR3xyx6Z0c/O3dLerWqmcH86U0D0Rh8OD3aPjJanyjmIfAH95WcvqOFr22ut3ASfhtpOWInDToMF+v/sl3rtk5Urc57VIyUqFj0ibELfa9vu/31atdzEhpCUdyXq430RIargbsm6fu2Won1xQ0GfyQKxBYtdghSELd/G/T4YkNYYDHtCS5p9VZqoPnaKSZ+ul6i6oJOfj8aE5hBHMZVUXGd4o72n0vAWtnu2EH5U1UHLnFbWw++PRwxoBdlv6c3p+9sdqfwAs+3zxjDTdRlHTtYNu20FXEesjtFHxnKsFb+gAw/2o=
