version: "3.9"
services:
  bracegirdle:
    build:
      context: .
      dockerfile: ./config/docker/bracegirdle.Dockerfile
    command: bash -c "bundle exec puma -C config/puma.rb"
    depends_on:
      - postgres
    volumes:
      - .:/var/www/bracegirdle
  nginx:
    build:
      context: .
      dockerfile: ./config/docker/nginx.Dockerfile
    depends_on:
      - bracegirdle
    ports:
      - 80:80