activities:
  complaint:
    color: 'danger'
    added:
      icon: 'icon ion-ios-add-circle'
      text: 'received a <%= link_to "complaint", activity.object %> against <%= activity.object.cemetery&.name || activity.object.cemetery_alternate_name %>'
      title: 'Received new complaint'
  cemeteryinspection:
    color: 'primary'
    completed:
      icon: 'icon ion-ios-flashlight'
      text: 'completed an <%= link_to "inspection", show_inspection_cemetery_path(activity.object.cemetery, activity.object) %> of <%= activity.object.cemetery.name %>'
      title: 'Completed an inspection'
  note:
    color: 'orange'
    comment:
      icon: 'fas fa-comment'
      text: 'commented on <%= note_link(activity.object) %>'
      title: 'Added a note'
  notice:
    color: 'danger'
    issued:
      icon: 'icon ion-ios-mail'
      text: 'issued Notice of Non-Compliance <%= link_to "##{activity.object.notice_number}", activity.object %> to <%= activity.object.cemetery.name %>'
      title: 'Issued notice'
    response:
      icon: 'icon ion-ios-mail-open'
      text: 'received a response to Notice of Non-Compliance <%= link_to "##{activity.object.notice_number}", activity.object %> from <%= activity.object.cemetery.name %>'
      title: 'Received response to notice'
  rules:
    color: 'teal'
    approved:
      icon: 'icon ion-ios-thumbs-up'
      text: 'approved <%= link_to "rules", activity.object %> for <%= activity.object.cemetery.name %>'
      title: 'Approved rules'
    assigned:
      icon: 'fas fa-user-plus'
      text: 'assigned <%= link_to "rules", activity.object %> for <%= activity.object.cemetery.name %> to <%= activity.object.investigator.name %>'
      title: 'Assigned rules'
    revision_received:
      icon: 'fas fa-envelope-open'
      text: 'received a revision to <%= link_to "rules", activity.object %> for <%= activity.object.cemetery.name %>'
      title: 'Received rules revision'
    revision_requested:
      icon: 'fas fa-user-edit'
      text: 'requested a revision to <%= link_to "rules", activity.object %> for <%= activity.object.cemetery.name %>'
      title: 'Requested rules revision'
    uploaded:
      icon: 'icon ion-ios-cloud-upload'
      text: 'uploaded new <%= link_to "rules", activity.object %> for <%= activity.object.cemetery.name %>'
      title: 'Uploaded new rules'
  restoration:
    color: 'indigo'
    processed:
      icon: 'icon ion-ios-clipboard'
      text: 'processed a <%= link_to("restoration application", send("#{activity.object.type.downcase}_path", activity.object.id)) %> for <%= activity.object.cemetery.name %>'
      title: 'Processed restoration application'
    received:
      icon: 'fas fa-satellite-dish'
      text: 'received a <%= link_to("restoration application", send("#{activity.object.type.downcase}_path", activity.object.id)) %> for <%= activity.object.cemetery.name %>'
      title: 'Received restoration application'
    reviewed:
      icon: 'fas fa-glasses'
      text: 'reviewed a <%= link_to("restoration application", send("#{activity.object.type.downcase}_path", activity.object.id)) %> for <%= activity.object.cemetery.name %>'
      title: 'Reviewed restoration application'