activities:
  complaint:
    color: 'primary'
    add:
      icon: 'icon ion-ios-add-circle'
      text: 'received a complaint against {{cemetery.name}}'
      title: 'Received new complaint'
  rules:
    color: 'teal'
    approval:
      icon: 'icon ion-ios-thumbs-up'
      text: 'approved rules for {{cemetery.name}}'
      title: 'Approved rules'
    upload:
      icon: 'icon ion-ios-cloud-upload'
      text: 'uploaded new rules for {{cemetery.name}}'
      title: 'Uploaded new rules'