activities:
  complaint:
    color: 'primary'
    add:
      icon: 'icon ion-ios-add-circle'
      text: 'received a <%= link_to "complaint", activity.object %> against <%= activity.object.cemetery.name %>'
      title: 'Received new complaint'
  notice:
    color: 'danger'
    issue:
      icon: 'icon ion-ios-mail'
      text: 'issued a <%= link_to "Notice of Non-Compliance", activity.object %> to <%= activity.object.cemetery.name %>'
      title: 'Issued notice'
    response:
      icon: 'icon ion-ios-mail-open'
      text: 'received a response to a <%= link_to "Notice of Non-Compliance", activity.object %> from <%= activity.object.cemetery.name %>'
      title: 'Received response to notice'
  rules:
    color: 'teal'
    approval:
      icon: 'icon ion-ios-thumbs-up'
      text: 'approved <%= link_to "rules", activity.object %> for <%= activity.object.cemetery.name %>'
      title: 'Approved rules'
    upload:
      icon: 'icon ion-ios-cloud-upload'
      text: 'uploaded new <%= link_to "rules", activity.object %> for <%= activity.object.cemetery.name %>'
      title: 'Uploaded new rules'
  restoration:
    color: 'indigo'
    processed:
      icon: 'icon ion-ios-clipboard'
      text: 'processed a <%= link_to("restoration application", restoration_path(activity.object.id, type: activity.object.application_type)) %> for <%= activity.object.cemetery.name %>'
      title: 'Processed restoration application'
    received:
      icon: 'fas fa-satellite-dish'
      text: 'received a <%= link_to("restoration application", restoration_path(activity.object.id, type: activity.object.application_type)) %> for <%= activity.object.cemetery.name %>'
      title: 'Received restoration application'
    reviewed:
      icon: 'fas fa-glasses'
      text: 'reviewed a <%= link_to("restoration application", restoration_path(activity.object.id, type: activity.object.application_type)) %> for <%= activity.object.cemetery.name %>'
      title: 'Reviewed restoration application'