activities:
  complaint:
    color: 'primary'
    add:
      icon: 'icon ion-ios-add-circle'
      text: 'received a <%= link_to "complaint", activity.object %> against <%= activity.object.cemetery.name %>'
      title: 'Received new complaint'
  rules:
    color: 'teal'
    approval:
      icon: 'icon ion-ios-thumbs-up'
      text: 'approved <%= link_to "rules", activity.object %> for <%= activity.object.cemetery.name %>'
      title: 'Approved rules'
    upload:
      icon: 'icon ion-ios-cloud-upload'
      text: 'uploaded new <%= link_to "rules", activity.object %> for <%= activity.object.cemetery.name %>'
      title: 'Uploaded new rules'