---
letterhead:
  governor: Andrew M. Cuomo
  secretary_of_state: Rossana Rosado
  attorney_general: Letitia James
  commissioner_of_health: Dr. Howard A. Zucker
  secretary_of_state_designee: Mark Pattison
  attorney_general_designee: Jill F. Faber, Esq.
  commissioner_of_health_designee: Thomas Fuller
  director: Lewis A. Polishook
  assistant_director: Alicia Young
