notifications:
  complaint:
    added:
      text: 'assigned a complaint to you against <%= notification.object.cemetery.name %>'
  note:
    comment:
      mailer: 'note_comment_email'
      text: 'added a comment to <%= note_text(notification.object) %>'
  restoration:
    received:
      text: 'assigned a restoration application to you for <%= notification.object.cemetery.name %>'
  rules:
    assigned:
      text: 'assigned you new rules for <%= notification.object.cemetery.name %>'
    uploaded:
      text: 'uploaded new rules for <%= notification.object.cemetery.name %>'