notifications:
  complaint:
    added:
      text: &complaint_assignment 'assigned a complaint to you against <%= notification.object.cemetery.name %>'
    assigned:
      text: *complaint_assignment
    reassigned:
      text: *complaint_assignment
    update_requested:
      text: 'requested an update on a complaint against <%= notification.object.cemetery.name %>'
  note:
    comment:
      mailer: 'note_comment_email'
      text: 'added a comment to <%= note_text(notification.object) %>'
  restoration:
    received:
      text: 'assigned a restoration application to you for <%= notification.object.cemetery.name %>'
  rulesapproval:
    assigned:
      text: 'assigned you new rules for approval from <%= notification.object.cemetery.name %>'
    uploaded:
      text: 'uploaded new rules for <%= notification.object.cemetery.name %>'